### ISSUE TITLE
Build Command Missing for Website Productions

### ISSUE THREAD

**Issue by piyush97** [piyush97/DSC-Website#16]
```sh
 npm start
> dsc-website@1.0.0 start /home/travis/build/piyush97/DSC-Website
> node server.js
/home/travis/build/piyush97/DSC-Website/server.js:38
    .then(() => console.log('Database connected!'))
           ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/home/travis/.nvm/v0.10.48/bin/node" "/home/travis/.nvm/v0.10.48/bin/npm" "start"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! dsc-website@1.0.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the dsc-website@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the dsc-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dsc-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls dsc-website
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/piyush97/DSC-Website/npm-debug.log
The command "npm start" exited with 1.
Done. Your build exited with 1.
```

**Comment by piyush97** [comment]
@RohitNagraj 	Adding npm build with node server.js doesn't make sense

**Comment by RohitNagraj** [comment]
Yeah, I realized that. But not very sure what's to be done. Will figure it out.

**Comment by piyush97** [comment]
What static site generator are you using?

**Comment by RohitNagraj** [comment]
I don't think we are using any currently.

**Comment by raghavddps2** [comment]
npm start as well as npm run build works now.
